import { StyleSheet } from "react-native";

export function createInviteStyles(colors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.textDark,
      flex: 1,
      textAlign: "center",
    },
    iconButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.lightGreen,
      alignItems: "center",
      justifyContent: "center",
    },
    content: {
      padding: 24,
      alignItems: "center",
    },
    title: {
      fontSize: 22,
      fontWeight: "700",
      color: colors.textDark,
      marginBottom: 8,
      textAlign: "center",
    },
    subtitle: {
      fontSize: 14,
      color: colors.textMuted,
      textAlign: "center",
      lineHeight: 20,
      marginBottom: 24,
    },
    qrCard: {
      backgroundColor: colors.white,
      borderRadius: 20,
      padding: 20,
      alignItems: "center",
      elevation: 2,
      width: "100%",
    },
    qrImage: {
      width: 240,
      height: 240,
      backgroundColor: colors.white,
    },
    name: {
      marginTop: 16,
      fontSize: 18,
      fontWeight: "700",
      color: colors.textDark,
    },
    phone: {
      marginTop: 4,
      fontSize: 14,
      color: colors.textMuted,
    },
    shareBtn: {
      marginTop: 20,
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 24,
      width: "100%",
      alignItems: "center",
    },
    shareText: {
      color: colors.white,
      fontWeight: "700",
      fontSize: 16,
    },
    hint: {
      marginTop: 16,
      fontSize: 13,
      color: colors.textMuted,
      textAlign: "center",
      lineHeight: 18,
    },
    camera: {
      flex: 1,
    },
    scanHint: {
      position: "absolute",
      bottom: 48,
      left: 24,
      right: 24,
      backgroundColor: "rgba(0,0,0,0.55)",
      borderRadius: 12,
      padding: 14,
    },
    scanHintText: {
      color: colors.white,
      textAlign: "center",
      fontSize: 14,
    },
    topBackBtn: {
      position: "absolute",
      top: 16,
      left: 16,
      zIndex: 2,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "rgba(0,0,0,0.45)",
      alignItems: "center",
      justifyContent: "center",
    },
    permissionBox: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 24,
    },
    permissionText: {
      fontSize: 16,
      textAlign: "center",
      marginBottom: 20,
      color: colors.textDark,
    },
    permissionBtn: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 12,
    },
    permissionBtnText: {
      color: colors.white,
      fontWeight: "700",
    },
  });
}
