import { StyleSheet } from "react-native";

export function createSettleBillStyles(colors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    loadingText: {
      marginTop: 12,
      color: colors.textMuted,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    headerBackBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.lightGreen,
    },
    headerCenter: {
      flex: 1,
      alignItems: "center",
      paddingHorizontal: 8,
    },
    title: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.textDark,
    },
    headerSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
      textAlign: "center",
      flexShrink: 1,
    },
    headerNameRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
      gap: 6,
      maxWidth: "100%",
    },
    editNameBtn: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.lightGreen,
    },
    renameInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      color: colors.textDark,
      backgroundColor: colors.backgroundAlt,
      marginBottom: 20,
    },
    headerTotal: {
      alignItems: "flex-end",
      minWidth: 72,
    },
    headerTotalLabel: {
      fontSize: 10,
      fontWeight: "700",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    headerTotalValue: {
      fontSize: 15,
      fontWeight: "800",
      color: colors.primaryDark,
      marginTop: 2,
    },
    warningText: {
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 4,
      color: colors.danger,
      fontSize: 13,
      lineHeight: 18,
    },
    statusBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 4,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    statusBannerClosed: {
      borderColor: colors.primary,
      backgroundColor: colors.lightGreen,
    },
    statusBannerReopened: {
      borderColor: colors.primary,
      backgroundColor: colors.lightGreen,
    },
    statusBannerIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.lightGreen,
      alignItems: "center",
      justifyContent: "center",
    },
    statusBannerText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textDark,
      fontWeight: "500",
    },
    participantsSection: {
      paddingTop: 10,
      paddingBottom: 4,
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    participantsLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.4,
      marginLeft: 16,
      marginBottom: 6,
    },
    participantsStripWrap: {
      flexGrow: 0,
    },
    participantsStrip: {
      paddingHorizontal: 16,
      paddingBottom: 10,
      gap: 8,
      flexDirection: "row",
      alignItems: "center",
    },
    participantChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      maxWidth: 200,
      minHeight: 36,
    },
    chip_open: {
      backgroundColor: colors.backgroundAlt,
      borderColor: colors.border,
    },
    chip_closed: {
      backgroundColor: colors.lightGreen,
      borderColor: colors.primary,
    },
    chip_settled: {
      backgroundColor: colors.lightGreen,
      borderColor: colors.primaryDark,
    },
    chip_reopened: {
      backgroundColor: colors.lightGreen,
      borderColor: colors.primary,
      borderStyle: "dashed",
    },
    statusDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      marginRight: 6,
    },
    dot_open: {
      backgroundColor: colors.muted,
    },
    dot_closed: {
      backgroundColor: colors.primary,
    },
    dot_settled: {
      backgroundColor: colors.primaryDark,
    },
    chipReopenedIcon: {
      marginRight: 4,
    },
    chipReopenedTag: {
      marginLeft: 5,
      fontSize: 9,
      fontWeight: "700",
      color: colors.primary,
      textTransform: "uppercase",
    },
    chipName: {
      flexShrink: 1,
      fontSize: 14,
      fontWeight: "600",
      color: colors.textDark,
    },
    chipActionBtn: {
      marginLeft: 5,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      minWidth: 26,
      height: 26,
      paddingHorizontal: 6,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.white,
    },
    chipActionBtnPrimary: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    chipActionBtnDisabled: {
      opacity: 0.55,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 8,
    },
    container: {
      flex: 1,
    },
    card: {
      backgroundColor: colors.white,
      marginBottom: 12,
      padding: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderLight,
      shadowColor: colors.shadow,
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    itemHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    itemHeaderLeft: {
      flex: 1,
      marginRight: 10,
    },
    itemName: {
      fontSize: 17,
      fontWeight: "700",
      color: colors.textDark,
      marginBottom: 4,
    },
    itemMeta: {
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 17,
    },
    qtyBadge: {
      backgroundColor: colors.lightGreen,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      alignItems: "center",
      minWidth: 52,
    },
    qtyBadgeValue: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.primaryDark,
    },
    qtyBadgeLabel: {
      fontSize: 9,
      fontWeight: "700",
      color: colors.primary,
      textTransform: "uppercase",
      marginTop: 1,
    },
    progressTrack: {
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.borderLight,
      marginBottom: 12,
      overflow: "hidden",
    },
    progressFill: {
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    rowHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 6,
      paddingHorizontal: 8,
      marginBottom: 4,
    },
    rowHeaderText: {
      fontSize: 10,
      fontWeight: "700",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    rowHeaderQty: {
      textAlign: "center",
      width: "100%",
    },
    rowHeaderAmount: {
      textAlign: "right",
      width: "100%",
    },
    myRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.lightGreen,
      paddingVertical: 8,
      paddingHorizontal: 8,
      borderRadius: 12,
      width: "100%",
      marginVertical: 3,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    mylockRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 8,
      borderRadius: 12,
      width: "100%",
      marginVertical: 3,
      backgroundColor: colors.backgroundAlt,
    },
    personCell: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
    },
    avatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.lightGreen,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 8,
    },
    avatarYou: {
      backgroundColor: colors.primary,
    },
    avatarText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.primaryDark,
    },
    avatarTextYou: {
      color: colors.white,
    },
    youLabel: {
      flex: 1,
      fontWeight: "700",
      color: colors.primaryDark,
      fontSize: 14,
    },
    otherName: {
      flex: 1,
      color: colors.textDark,
      fontSize: 14,
      fontWeight: "500",
    },
    qtyInput: {
      width: 52,
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderRadius: 10,
      paddingVertical: 6,
      paddingHorizontal: 4,
      textAlign: "center",
      backgroundColor: colors.white,
      color: colors.primaryDark,
      fontSize: 14,
      fontWeight: "700",
    },
    qtyPill: {
      width: 52,
      minHeight: 34,
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    qtyPillYou: {
      backgroundColor: "transparent",
      borderWidth: 0,
    },
    qtyPillOther: {
      backgroundColor: "transparent",
      borderWidth: 0,
    },
    qtyPillText: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textMuted,
      textAlign: "center",
    },
    qtyPillTextYou: {
      color: colors.primaryDark,
    },
    amount: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textDark,
      textAlign: "right",
      width: "100%",
    },
    amountYou: {
      color: colors.primaryDark,
    },
    rowBase: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 2,
    },
    nameCol: {
      flex: 1,
      minWidth: 0,
    },
    qtyCol: {
      width: 64,
      alignItems: "center",
      justifyContent: "center",
    },
    amountCol: {
      width: 88,
      alignItems: "flex-end",
      justifyContent: "center",
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 16,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      backgroundColor: colors.white,
      shadowColor: colors.shadow,
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: -4 },
      elevation: 8,
    },
    youPayRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: colors.lightGreen,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    youPayLabel: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.primaryDark,
    },
    youPayAmount: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.primaryDark,
    },
    actionRow: {
      flexDirection: "row",
      gap: 10,
    },
    saveButton: {
      flex: 1,
      backgroundColor: colors.white,
      borderWidth: 2,
      borderColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: "center",
    },
    saveButtonText: {
      color: colors.primary,
      fontSize: 15,
      fontWeight: "700",
    },
    closeButton: {
      flex: 1,
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: "center",
    },
    actionButtonDisabled: {
      opacity: 0.6,
    },
    closeButtonDisabled: {
      opacity: 0.6,
    },
    closeButtonText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: "700",
    },
    confirmOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "center",
      alignItems: "center",
      padding: 24,
    },
    confirmBox: {
      width: "100%",
      backgroundColor: colors.white,
      borderRadius: 18,
      padding: 22,
      elevation: 4,
    },
    confirmTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.textDark,
      marginBottom: 10,
    },
    confirmMessage: {
      fontSize: 15,
      lineHeight: 22,
      color: colors.textMuted,
      marginBottom: 20,
    },
    confirmActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
    },
    confirmCancelButton: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 10,
      backgroundColor: colors.backgroundAlt,
    },
    confirmCancelText: {
      color: colors.textMuted,
      fontSize: 15,
      fontWeight: "600",
    },
    confirmPrimaryButton: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 10,
      backgroundColor: colors.primary,
    },
    confirmPrimaryText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: "700",
    },
  });
}
