import { StyleSheet } from "react-native";

export function createSettingsStyles(colors) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.textDark,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.lightGreen,
    alignItems: "center",
    justifyContent: "center",
  },
  profileCard: {
    backgroundColor: colors.white,
    margin: 20,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    elevation: 2,
    position: "relative",
  },
  profileEditButton: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.lightGreen,
    alignItems: "center",
    justifyContent: "center",
  },
  profileFormInner: {
    width: "100%",
    marginTop: 8,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.lightGreen,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  avatarText: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.primary,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textDark,
  },
  profilePhone: {
    fontSize: 14,
    color: colors.textMuted,
    marginTop: 4,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textMuted,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
    backgroundColor: colors.backgroundAlt,
    marginBottom: 14,
  },
  saveButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "700",
  },
  section: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textMuted,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  row: {
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    elevation: 1,
  },
  rowLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  rowIcon: {
    marginRight: 12,
  },
  rowLabel: {
    fontSize: 16,
    color: colors.textDark,
  },
  rowValue: {
    fontSize: 14,
    color: colors.textMuted,
  },
  themeRow: {
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 8,
    elevation: 1,
  },
  themeOptions: {
    flexDirection: "row",
    marginTop: 12,
  },
  themeOption: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.backgroundAlt,
    marginRight: 8,
  },
  themeOptionLast: {
    marginRight: 0,
  },
  themeOptionActive: {
    borderColor: colors.primary,
    backgroundColor: colors.lightGreen,
  },
  themeOptionText: {
    marginLeft: 8,
    fontSize: 15,
    fontWeight: "600",
    color: colors.textMuted,
  },
  themeOptionTextActive: {
    color: colors.primaryDark,
  },
  switchAccountButton: {
    backgroundColor: colors.white,
    marginHorizontal: 20,
    marginTop: 24,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  switchAccountText: {
    color: colors.primaryDark,
    fontSize: 16,
    fontWeight: "700",
  },
  logoutButton: {
    backgroundColor: colors.white,
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.dangerBorder,
  },
  logoutText: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: "700",
  },
  versionText: {
    textAlign: "center",
    color: colors.muted,
    fontSize: 12,
    marginTop: 24,
    marginBottom: 32,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "center",
    padding: 24,
  },
  modalCard: {
    backgroundColor: colors.white,
    borderRadius: 14,
    padding: 18,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.textDark,
    marginBottom: 8,
  },
  modalMessage: {
    color: colors.textMuted,
    marginBottom: 18,
    lineHeight: 20,
    fontSize: 14,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
  },
  modalCancelText: {
    color: colors.textMuted,
    fontWeight: "600",
  },
  modalConfirmText: {
    color: colors.primary,
    fontWeight: "700",
  },
});
}
